### ISSUE TITLE
什么时候可以支持mirai-api-http 2.0呢?

### ISSUE THREAD

**Issue by Cyl18** [theGravityLab/Hyperai#25]

**Comment by ac682** [comment]
这只是个基础设施库，mah2的适配器要自己实现，我个人维护了一个[CQHTTP](https://github.com/ac682.Hyperai.Clients.CQHTTP)，可以找照这个自己写mah2的适配器（写的很丑就是了）。

**Comment by Cyl18** [comment]
好吧
